- README.md
I have added my name to the top of the readme file. This should raise my profile in the company and get me a raise.
> added a mention to the readme

- git-flow.md
I have added a new file that includes a link about Git Flow. Might be useful :)
> added comment to git-flow file

- index.html
> Typo correction and bold text

- index.html
Here is update on image placeholders in the content area
> Marats branch

- index.html
changed the pointer to be a local file, so there is no white background anymore, added a style tag affecting every img to make it flip when hovered over, please advise best course of action mr james.
> flip images

- index.html
- js/password.js
Hi James! I just added a password input, it has a script in javascript. It has a red background if it has less than 10 characters, an orange if less than 18 and green if more, and obvs with a cat based message!
Thanks
Vicki
> added a password input

- css/customisations.css
- index.html
MEOW MEOW MEOW now has a feint orange shadow surrounding it, it looks terrible, but it was requested by Overseer Oliver Ward.
> orange shadow

- index.html
To fix the images on the slider, I removed the img that had been added to the slider. This means that the background img can now been seen.
> fixed images on the slider

- contact.html
Added link to home page on the contact page. href link on the logo and on the first "cats" navbar. Removed link on the first dropdown "cats".
> fixed link to home page

- README.md
Added some important information on README file.
> modify readme file, closes #458

- terms.html
I have added a link on the terms page to take the user back to the home page
> added link to terms page

- index.html
- sitecreators.css
- sitecreators.html
Hi!
So I added a page for the site creators. I added a link to it in the main li menu bit at the top of the main index page, hopefully it works....
Thanks
Vicki
> added new page for site creators

- css/customisations.css
As requested, I have created an electric blue glow around img-circle. I have also set the border as 0px as it was ruining the effect!
> added electric blue around img circles

- index.html
I have deleted the img tags containing the Nick Cage gifs.
Thanks
Vicki
> got rid of nick cage gif

- index.html
> added blog link

- index.html
Added some cat video on the home page.
> add video - closes #482 and #483

- css/customisations.css
- index.html
changed the look of the footer
> changed footer css

- contact.html
removed cats and cats in space from contact page as requested
> removed cats and cats in space

- sitecreators.css
- sitecreators.html
Added a button, styled it, let me know what you think boss.
> Creatorsbacktohomepagebutton

- contact.html
> removed code instead of commenting out

- css/customisations.css
I have added a better border to the nav. This makes the nav more in keeping with the rest of the site
> added a better border to the nav

- css/customisations.css
- index.html
Adds a section of testimonials on home page.
> Add testimonials - closes #487

- css/customisations.css
- index.html
> Testimonials

- css/customisations.css
turn the repeated pizza cat faces into one image
> made pizza cat into one image

- css/customisations.css
Reverts develop-me/git-simple#531
> Revert "font colors and pizza cat image"

- css/customisations.css
Reverts develop-me/git-simple#533
> Cat pizza fix

- contact.html
> cleaned up content header

- index.html
Fixed the slider by reverting it back to some older code.
> fixed slider

- index.html
added a counter below the meow header
> counter added

- borderanimation.css
- borderanimation.html
- index.html
I put in a link to a page with border animations.
> Borderanimation

- css/customisations.css
> hover animation on circular images in index.html

- about.html
Footer added to bottom of about page as requested.
> 859 add About page Footer

- css/customisations.css
makes all children of no-animate class also no animate
> fixes blog footer moving around, 

- about.html
- blog.html
- contact.html
- css/customisations.css
- index.html
- policy.html
- terms.html
Made contact form and edited other pages to link to it.
> Contact form

- index.html
html code tidied up, all indented correctly
issue #877
> 877 - tidy up index.html code

- css/customisations.css
- reviews.html
created content for the review page
> review page

- blog.html
- contact.html
- css/customisations.css
- index.html
- signUp.html
Just a sign up page for issue(Speedy Blog Page - Signup Button #861) to send an email to a particular email addres
> signUp page added

- blog.html
- contact.html
- signUp.html
contact form "action" to send it as email and validating email #883
> added validation to email and form action added

- blog.html
- css/carousel.css
Fixed an issue with the blog header text that would bump some of it off the screen when resizing
> Blog header resize

- css/cursor.css
- css/customisations.css
- index.html
Moved cursor property into customisations.css, added cursor property to anchor tag hovers, and deleted cursor.css (now redundant).
> Updated cursor property - #867

- index.html
> icon added again

- css/carousel.css
> some of the font color to brown

- index.html
> footer changes

- index.html
> updated branch - MERGE MY BRANCH!!

- index.html
> final version

- index.html
changed the picture on the carousel, now it's a cat not a blobfish.
> change picture

- index.html
new animal image and text for that image
> new animal image and placeholder text

- index.html
> new animal image

- index.html
> added sophisticated blob

- index.html
changed cat to otter image and text
> changed otter image

- css/bootstrap.css
- css/carousel.css
Please check the lines and lines.
> line height change

- css/customisations.css
- index.html
> added hidden Christopher Walken image with required CSS

- index.html
> Add cat video

- css/mystyle.css
- index.html
Linked mystyle page to index and edited a few things to hot pink!
> Harry - Linked mystyle.css into index.html - started project hot pink

- index.html
> added paragraph to footer specifying the year which it was edited
